- name: installer Nginx
  package:
    name: nginx
    state: present

- name: Démarrer Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name : Configuration Nginx
  template:
    src: wiki.j2
    dest: /etc/nginx/sites-available/wiki

- name: lien symbolique
  command: ln -s /etc/nginx/sites-available/wiki /etc/nginx/sites-enabled

- name: Désactivation lien default
  command: unlink /etc/nginx/sites-enabled/default
  notify: restart nginx
