- name : Copie de LocalSettings.php
  copy:
    src: files/LocalSettings.php
    dest: /appli/projects/md1/nginx

- name: Lancer le script d'update de la base de données
  command: php "/appli/projects/md1/nginx/maintenance/update.php"

- name: Import images
  command: php "/appli/projects/md1/nginx/maintenance/importImages.php" "/appli/wikidevops/LIVR/LoGo"
  notify: restart nginx
