- name: Installation php7.4
  package:
    name: "{{ item }}"
    state: present
  loop:
    - php7.4
    - php7.4-fpm
    - php7.4-mysql
    - php7.4-xml
    - php7.4-curl
    - php7.4-gd
    - php7.4-intl
    - php7.4-json
    - php7.4-mbstring

- name: Renommer le fichier wiki en wikiold1.24
  command: mv /etc/nginx/sites-enabled/wiki /etc/nginx/sites-enabled/wikiold1.24

- name : Configuration Nginx pour php 7.4
  template:
    src: wiki.j2
    dest: /etc/nginx/sites-available/wiki
