- name: Ajout repository de php
      apt_repository:
        repo: 'ppa:ondrej/php'

- name: Installation php5.6
  package:
    name: "{{ item }}"
    state: present
  loop:
    - php5.6
    - php5.6-fpm
    - php5.6-mysql
    - php5.6-xml
    - php5.6-curl
    - php5.6-gd
    - php5.6-intl
    - php5.6-json
    - php5.6-mbstring

- name: Désinstallation Apache
  apt:
    name: apache2
    state: absent
    purge: yes
